# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "LiMengtian"
description: > # this means to ignore newlines until "email:"
   LiMengtian - LiMengtian

email: mengtian.li@nearfor.me
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'LiMengtian'
author: 'LiMengtian'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/llmmtt
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
